/**
 * Generates styles/font.css with the typeface inlined as a data URI.
 *
 * PRODUCT.md pins two things that rule out a font CDN: zero runtime
 * dependencies, and the app must run from `file://`. A relative @font-face URL
 * would satisfy the first but Chrome treats file:// subresources as opaque
 * origins and refuses them, so the face is embedded instead. One file, no
 * request, no origin to argue with.
 *
 * The output is committed. This script is run by hand when the face changes; it
 * is not a build step.
 *
 *   node tools/embed-font.mjs
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const woff2 = join(root, 'assets', 'fonts', 'jost-latin-var.woff2');
const out = join(root, 'styles', 'font.css');

const bytes = readFileSync(woff2);
const b64 = bytes.toString('base64');

const css = `/* Generated by tools/embed-font.mjs — do not edit by hand.
 *
 * Jost* by Owen Earl / indestructible type*, licensed SIL Open Font License 1.1.
 * Full licence text: assets/fonts/Jost-OFL.txt
 *
 * Jost* is a geometric sans drawn after Futura, the face that came out of the
 * same moment as the Bauhaus preliminary course this interface is built on.
 * Latin subset, variable weight 400-700, embedded so the page works offline and
 * from the filesystem.
 */
@font-face {
  font-family: 'Jost';
  font-style: normal;
  font-weight: 400 700;
  font-display: swap;
  src: url(data:font/woff2;base64,${b64}) format('woff2');
  unicode-range: U+0000-00FF, U+0131, U+0152-0153, U+02BB-02BC, U+02C6, U+02DA,
    U+02DC, U+0304, U+0308, U+0329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193,
    U+2212, U+2215, U+FEFF, U+FFFD;
}
`;

writeFileSync(out, css, 'utf8');
console.log(`wrote ${out} — ${bytes.length} bytes of woff2 -> ${css.length} bytes of css`);
